services:
  app:
    image: ghcr.io/opensanctions/yente:4.1.0
    ports:
      - "127.0.0.1:8000:8000"
    # If you want to index data from the host machine as a custom dataset,
    # create a volume mount here to make that data accessible from the 
    # container:
    # volumes:
    #   - "/path/on/the/host/computer:/data"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s
    deploy:
      mode: replicated
      # Run multiple instances for better scale:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

volumes:
  index-os-data: null
